name: Send analysis report to channel
on:
  push:
    branches:
      - main
jobs:
  run:
    name: Send report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Set variables
        run: |
          REPORT=$(cat '${{ env.GITHUB_WORKSPACE }}Design Reporting/Report.txt' | sed ':a;N;$!ba;s/\n/\\n/g' )
          echo "REPORT<<EOF" >> $GITHUB_ENV
          echo "$REPORT" >> $GITHUB_ENV
          DATETIME=$(date)
          echo "EOF" >> $GITHUB_ENV
          echo "DATETIME=$DATETIME" >> $GITHUB_ENV

      - name: Send Report
        id: send_report
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "*${{ env.DATETIME }}*"


      - name: Print Details
        run: |
          echo ${ toJSON({steps.send_report.outputs) }}
          echo ${ {toJSON(steps.send_report.ok) }}
