name: Post an inline text message
on:
  push:
    branches:
      - main
jobs:
  run:
    name: Leave a kind message after updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Set variables
        run: |
          REPORT=$(cat '${{ env.GITHUB_WORKSPACE }}Design Reporting/Report.txt')
          echo "MULTI_LINES_TEXT_ENV_VAR<<EOF" >> $GITHUB_ENV
          echo "REPORT $REPORT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Greet the reader
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "${{ env.REPORT }}"
