name: Send analysis report to channel
on:
  push:
    branches:
      - main
jobs:
  run:
    name: Send report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Set variables
        run: |
          REPORT=$(cat '${{ env.GITHUB_WORKSPACE }}Design Reporting/Report.txt' | sed ':a;N;$!ba;s/\n/\\n/g' )
          echo "REPORT<<EOF" >> $GITHUB_ENV
          echo "$REPORT" >> $GITHUB_ENV
          DATETIME=$(date)
          echo "EOF" >> $GITHUB_ENV
          echo "DATETIME=$DATETIME" >> $GITHUB_ENV

      - name: Post first message to Slack channel
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "**${{ env.DATETIME }}**"

      - name: Print Details
        continue-on-error: true
        run: |
          echo ${{ toJSON(steps.send_report.outputs) }}

      - name: Post text to a Slack channel
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACKBOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            thread_ts: ${{ steps.send_report.outputs.time}}
            text: "howdy <!channel>!"

